export const initialState = [
  {
    id: "1",
    name: "John Smith",
    designation: "Senior UI developer",
    exp: 11,
    technologies: ["XD", "Sketch", "Figma"],
    skills: ["UX", "UI", "Visual"],
    avaibility: "3",
    location: ["Indore", "Pune"],
    isOpenForRelocation: false,
    message: "",
  },
  {
    id: "11",
    name: "Mark Miller",
    designation: "Lead developer",
    exp: 12,
    technologies: ["Angular", "Sketch", "Figma"],
    skills: ["UX", "UI"],
    avaibility: "4",
    location: ["Indore", "Pune", "Hydrabad"],
    isOpenForRelocation: true,
    message: "",
  },
  {
    id: "12",
    name: "Thomas Hall",
    designation: "Senior Lead developer",
    exp: 3,
    technologies: ["Angular", "C++", "Figma"],
    skills: ["UX", "UI", "Java", "C"],
    avaibility: "4",
    location: ["Banglore", "Pune"],
    isOpenForRelocation: true,
    message: "",
  },
  {
    id: "14",
    name: "John White",
    designation: "Senior UI developer",
    exp: 5,
    technologies: ["Figma"],
    skills: ["UX", "UI"],
    avaibility: "4",
    location: ["Pune"],
    isOpenForRelocation: false,
    message: "",
  },
  {
    id: "30",
    name: "Mark Kargo",
    designation: "Senior UI developer",
    exp: 2,
    technologies: ["Figma", "Sketch", "XD"],
    skills: ["UX", "UI", "Java"],
    avaibility: "4",
    location: ["Pune"],
    isOpenForRelocation: true,
    message: "",
  },
  {
    id: "19",
    name: "Leo White",
    designation: "Senior Java developer",
    exp: 10,
    technologies: ["Figma", "Angular", "C++"],
    skills: ["UX", "UI", "C"],
    avaibility: "4",
    location: ["Pune", "Indore", "Banglore", "Hydrabad"],
    isOpenForRelocation: false,
    message: "",
  },
  {
    id: "17",
    name: "John Walker",
    designation: "Senior UX developer",
    exp: 15,
    technologies: ["XD", "Sketch", "Figma", "Angular", "C++"],
    skills: ["UX", "UI", "Visual", "Java", "C"],
    avaibility: "4",
    location: ["Pune", "Indore", "Banglore", "Hydrabad"],
    isOpenForRelocation: true,
    message: "",
  },
  {
    id: "181",
    name: "Syn Kkera",
    designation: "UX developer",
    exp: 20,
    technologies: ["XD", "Sketch", "Angular"],
    skills: ["UX", "UI", "Visual"],
    avaibility: "4",
    location: ["Pune", "Indore", "Banglore", "Hydrabad"],
    isOpenForRelocation: true,
    message: "",
  },
  {
    id: "182",
    name: "Mew Tara",
    designation: "API developer",
    exp: 8,
    technologies: ["Figma", "C++"],
    skills: ["Java", "C"],
    avaibility: "4",
    location: ["Pune", "Indore", "Hydrabad"],
    isOpenForRelocation: true,
    message: "",
  },
  {
    id: "183",
    name: "Mew Tara",
    designation: "API developer",
    exp: 10,
    technologies: ["Figma", "C++"],
    skills: ["Java", "C"],
    avaibility: "4",
    location: ["Pune", "Hydrabad"],
    isOpenForRelocation: true,
    message: "",
  },
];

export const skillData = ["UX", "UI", "Visual", "Java", "C"];
export const techData = ["XD", "Sketch", "Figma", "Angular", "C++"];
export const locationData = ["Pune", "Indore", "Banglore", "Hydrabad"];
export const marksData = [
  {
    value: 0,
    label: "0",
  },

  {
    value: 20,
    label: "20",
  },
];
